export interface ShopItem {
  id: string;
  name: string;
  image: string;
  category: "houses" | "tents" | "decor" | "archer-towers";
  price: number;
  description: string;
  isStarter?: boolean;
}

export const shopItems: ShopItem[] = [
  // Houses - Based on visual complexity and luxury
  {
    id: "house-1",
    name: "Noble Manor",
    image: "/village-items/houses/1.png",
    category: "houses",
    price: 100,
    description: "A prestigious noble estate",
    isStarter: true,
  },
  {
    id: "house-2",
    name: "Cozy Cabin",
    image: "/village-items/houses/2.png",
    category: "houses",
    price: 150,
    description: "A comfortable family home",
    isStarter: true,
  },
  {
    id: "house-3",
    name: "Modest House",
    image: "/village-items/houses/3.png",
    category: "houses",
    price: 200,
    description: "A simple but elegant residence",
  },
  {
    id: "house-4",
    name: "Charming Home",
    image: "/village-items/houses/4.png",
    category: "houses",
    price: 250,
    description: "A quaint and lovely dwelling",
  },
  {
    id: "house-5",
    name: "Elegant Manor",
    image: "/village-items/houses/5.png",
    category: "houses",
    price: 300,
    description: "A refined and sophisticated home",
  },
  {
    id: "house-6",
    name: "Grand Estate",
    image: "/village-items/houses/6.png",
    category: "houses",
    price: 350,
    description: "A magnificent family estate",
  },
  {
    id: "house-7",
    name: "Royal Palace",
    image: "/village-items/houses/7.png",
    category: "houses",
    price: 400,
    description: "A majestic royal residence",
  },
  {
    id: "house-8",
    name: "Simple Cottage",
    image: "/village-items/houses/8.png",
    category: "houses",
    price: 450,
    description: "A humble dwelling",
  },
  {
    id: "house-9",
    name: "Imperial Castle",
    image: "/village-items/houses/9.png",
    category: "houses",
    price: 500,
    description: "A grand imperial fortress",
  },
  {
    id: "house-10",
    name: "Royal Castle",
    image: "/village-items/houses/10.png",
    category: "houses",
    price: 550,
    description: "A splendid royal castle",
  },
  {
    id: "house-11",
    name: "Imperial Palace",
    image: "/village-items/houses/11.png",
    category: "houses",
    price: 600,
    description: "An imperial palace of grandeur",
  },
  {
    id: "house-12",
    name: "Royal Fortress",
    image: "/village-items/houses/12.png",
    category: "houses",
    price: 650,
    description: "A fortified royal residence",
  },
  {
    id: "house-13",
    name: "Mystical Castle",
    image: "/village-items/houses/13.png",
    category: "houses",
    price: 700,
    description: "A castle shrouded in mystery",
  },
  {
    id: "house-14",
    name: "Enchanted Palace",
    image: "/village-items/houses/14.png",
    category: "houses",
    price: 750,
    description: "A palace touched by magic",
  },
  {
    id: "house-15",
    name: "Mystical Manor",
    image: "/village-items/houses/15.png",
    category: "houses",
    price: 800,
    description: "A manor of mystical power",
  },
  {
    id: "house-16",
    name: "Legendary Castle",
    image: "/village-items/houses/16.png",
    category: "houses",
    price: 850,
    description: "A castle of legendary renown",
  },
  {
    id: "house-17",
    name: "Ancient Citadel",
    image: "/village-items/houses/17.png",
    category: "houses",
    price: 900,
    description: "An ancient fortified city",
  },
  {
    id: "house-18",
    name: "Divine Palace",
    image: "/village-items/houses/18.png",
    category: "houses",
    price: 950,
    description: "A palace blessed by the gods",
  },
  {
    id: "house-19",
    name: "Celestial Castle",
    image: "/village-items/houses/19.png",
    category: "houses",
    price: 1000,
    description: "A castle from the heavens",
  },
  {
    id: "house-20",
    name: "Ethereal Mansion",
    image: "/village-items/houses/20.png",
    category: "houses",
    price: 1050,
    description: "A mansion of ethereal beauty",
  },
  {
    id: "house-21",
    name: "Mythical Palace",
    image: "/village-items/houses/21.png",
    category: "houses",
    price: 1100,
    description: "A palace from myths",
  },
  {
    id: "house-22",
    name: "Legendary Citadel",
    image: "/village-items/houses/22.png",
    category: "houses",
    price: 1150,
    description: "A citadel of legends",
  },
  {
    id: "house-23",
    name: "Celestial Palace",
    image: "/village-items/houses/23.png",
    category: "houses",
    price: 1200,
    description: "A palace from the stars",
  },
  {
    id: "house-24",
    name: "Ethereal Castle",
    image: "/village-items/houses/24.png",
    category: "houses",
    price: 1250,
    description: "A castle of ethereal grace",
  },
  {
    id: "house-25",
    name: "Mythical Fortress",
    image: "/village-items/houses/25.png",
    category: "houses",
    price: 1300,
    description: "A fortress from myths",
  },
  {
    id: "house-26",
    name: "Divine Citadel",
    image: "/village-items/houses/26.png",
    category: "houses",
    price: 1350,
    description: "A citadel blessed by divinity",
  },
  {
    id: "house-27",
    name: "Legendary Palace",
    image: "/village-items/houses/27.png",
    category: "houses",
    price: 1400,
    description: "A palace of legendary status",
  },

  // Tents - Based on size and complexity
  {
    id: "tent-1",
    name: "Basic Tent",
    image: "/village-items/tents/1.png",
    category: "tents",
    price: 50,
    description: "A simple camping tent",
    isStarter: true,
  },
  {
    id: "tent-2",
    name: "Comfortable Tent",
    image: "/village-items/tents/2.png",
    category: "tents",
    price: 75,
    description: "A cozy camping tent",
  },
  {
    id: "tent-3",
    name: "Deluxe Tent",
    image: "/village-items/tents/3.png",
    category: "tents",
    price: 100,
    description: "A spacious camping tent",
  },
  {
    id: "tent-4",
    name: "Luxury Tent",
    image: "/village-items/tents/4.png",
    category: "tents",
    price: 125,
    description: "A luxurious camping tent",
  },
  {
    id: "tent-5",
    name: "Premium Tent",
    image: "/village-items/tents/5.png",
    category: "tents",
    price: 150,
    description: "A premium camping tent",
  },
  {
    id: "tent-6",
    name: "Elite Tent",
    image: "/village-items/tents/6.png",
    category: "tents",
    price: 175,
    description: "An elite camping tent",
  },

  // Archer Towers - Based on defensive capabilities
  {
    id: "tower-1",
    name: "Basic Tower",
    image: "/village-items/archer-towers/1.png",
    category: "archer-towers",
    price: 200,
    description: "A simple defensive tower",
    isStarter: true,
  },
  {
    id: "tower-2",
    name: "Improved Tower",
    image: "/village-items/archer-towers/2.png",
    category: "archer-towers",
    price: 300,
    description: "An enhanced defensive tower",
  },
  {
    id: "tower-4",
    name: "Advanced Tower",
    image: "/village-items/archer-towers/4.png",
    category: "archer-towers",
    price: 400,
    description: "A sophisticated defensive tower",
  },
  {
    id: "tower-7",
    name: "Elite Tower",
    image: "/village-items/archer-towers/7.png",
    category: "archer-towers",
    price: 500,
    description: "An elite defensive tower",
  },

  // Decor Items - Based on visual complexity and rarity
  {
    id: "decor-1",
    name: "Simple Ornament",
    image: "/village-items/decor/decor_1.png",
    category: "decor",
    price: 25,
    description: "A basic decorative item",
    isStarter: true,
  },
  {
    id: "decor-2",
    name: "Elegant Ornament",
    image: "/village-items/decor/decor_2.png",
    category: "decor",
    price: 30,
    description: "A refined decorative piece",
  },
  {
    id: "decor-3",
    name: "Charming Decoration",
    image: "/village-items/decor/decor_3.png",
    category: "decor",
    price: 35,
    description: "A charming decorative item",
  },
  {
    id: "decor-4",
    name: "Lovely Ornament",
    image: "/village-items/decor/decor_4.png",
    category: "decor",
    price: 40,
    description: "A lovely decorative piece",
  },
  {
    id: "decor-5",
    name: "Fancy Decoration",
    image: "/village-items/decor/decor_5.png",
    category: "decor",
    price: 45,
    description: "A fancy decorative item",
  },
  {
    id: "decor-6",
    name: "Beautiful Ornament",
    image: "/village-items/decor/decor_6.png",
    category: "decor",
    price: 50,
    description: "A beautiful decorative piece",
  },
  {
    id: "decor-7",
    name: "Exquisite Decoration",
    image: "/village-items/decor/decor_7.png",
    category: "decor",
    price: 55,
    description: "An exquisite decorative item",
  },
  {
    id: "decor-8",
    name: "Luxurious Ornament",
    image: "/village-items/decor/decor_8.png",
    category: "decor",
    price: 60,
    description: "A luxurious decorative piece",
  },
  {
    id: "decor-9",
    name: "Premium Decoration",
    image: "/village-items/decor/decor_9.png",
    category: "decor",
    price: 65,
    description: "A premium decorative item",
  },
  {
    id: "decor-10",
    name: "Majestic Ornament",
    image: "/village-items/decor/decor_10.png",
    category: "decor",
    price: 70,
    description: "A majestic decorative piece",
  },
  {
    id: "decor-11",
    name: "Royal Decoration",
    image: "/village-items/decor/decor_11.png",
    category: "decor",
    price: 75,
    description: "A royal decorative item",
  },
  {
    id: "decor-12",
    name: "Imperial Ornament",
    image: "/village-items/decor/decor_12.png",
    category: "decor",
    price: 80,
    description: "An imperial decorative piece",
  },
  {
    id: "decor-13",
    name: "Mystical Decoration",
    image: "/village-items/decor/decor_13.png",
    category: "decor",
    price: 85,
    description: "A mystical decorative item",
  },
  {
    id: "decor-14",
    name: "Enchanted Ornament",
    image: "/village-items/decor/decor_14.png",
    category: "decor",
    price: 90,
    description: "An enchanted decorative piece",
  },
  {
    id: "decor-15",
    name: "Legendary Decoration",
    image: "/village-items/decor/decor_15.png",
    category: "decor",
    price: 95,
    description: "A legendary decorative item",
  },
  {
    id: "decor-16",
    name: "Divine Ornament",
    image: "/village-items/decor/decor_16.png",
    category: "decor",
    price: 100,
    description: "A divine decorative piece",
  },
  {
    id: "decor-17",
    name: "Celestial Decoration",
    image: "/village-items/decor/decor_17.png",
    category: "decor",
    price: 105,
    description: "A celestial decorative item",
  },
  {
    id: "decor-18",
    name: "Ethereal Ornament",
    image: "/village-items/decor/decor_18.png",
    category: "decor",
    price: 110,
    description: "An ethereal decorative piece",
  },
  {
    id: "decor-19",
    name: "Mystical Ornament",
    image: "/village-items/decor/decor_19.png",
    category: "decor",
    price: 115,
    description: "A mystical decorative item",
  },
  {
    id: "decor-20",
    name: "Enchanted Decoration",
    image: "/village-items/decor/decor_20.png",
    category: "decor",
    price: 120,
    description: "An enchanted decorative piece",
  },
  {
    id: "decor-21",
    name: "Legendary Ornament",
    image: "/village-items/decor/decor_21.png",
    category: "decor",
    price: 125,
    description: "A legendary decorative item",
  },

  // Trees - Based on size and visual complexity
  {
    id: "tree-1",
    name: "Majestic Tree",
    image: "/village-items/decor/tree_1.png",
    category: "decor",
    price: 40,
    description: "A grand and majestic tree",
  },
  {
    id: "tree-2",
    name: "Ancient Tree",
    image: "/village-items/decor/tree_2.png",
    category: "decor",
    price: 45,
    description: "An ancient and wise tree",
  },
  {
    id: "tree-3",
    name: "Mystical Tree",
    image: "/village-items/decor/tree_3.png",
    category: "decor",
    price: 50,
    description: "A tree of mystical power",
  },
  {
    id: "tree-4",
    name: "Enchanted Tree",
    image: "/village-items/decor/tree_4.png",
    category: "decor",
    price: 55,
    description: "A tree touched by magic",
  },
  {
    id: "tree-5",
    name: "Magical Tree",
    image: "/village-items/decor/tree_5.png",
    category: "decor",
    price: 60,
    description: "A tree of magical essence",
  },
  {
    id: "tree-6",
    name: "Sacred Tree",
    image: "/village-items/decor/tree_6.png",
    category: "decor",
    price: 65,
    description: "A tree of sacred power",
  },
  {
    id: "tree-7",
    name: "Divine Tree",
    image: "/village-items/decor/tree_7.png",
    category: "decor",
    price: 70,
    description: "A tree blessed by divinity",
  },
  {
    id: "tree-8",
    name: "Celestial Tree",
    image: "/village-items/decor/tree_8.png",
    category: "decor",
    price: 75,
    description: "A tree from the heavens",
  },
  {
    id: "tree-9",
    name: "Ethereal Tree",
    image: "/village-items/decor/tree_9.png",
    category: "decor",
    price: 80,
    description: "A tree of ethereal beauty",
  },
  {
    id: "tree-10",
    name: "Mythical Tree",
    image: "/village-items/decor/tree_10.png",
    category: "decor",
    price: 85,
    description: "A tree from myths",
  },
  {
    id: "tree-11",
    name: "Legendary Tree",
    image: "/village-items/decor/tree_11.png",
    category: "decor",
    price: 90,
    description: "A tree of legendary status",
  },
  {
    id: "tree-12",
    name: "Primordial Tree",
    image: "/village-items/decor/tree_12.png",
    category: "decor",
    price: 95,
    description: "A tree from the beginning of time",
  },
  {
    id: "tree-13",
    name: "World Tree",
    image: "/village-items/decor/tree_13.png",
    category: "decor",
    price: 100,
    description: "A tree that holds the world",
  },
  {
    id: "tree-14",
    name: "Cosmic Tree",
    image: "/village-items/decor/tree_14.png",
    category: "decor",
    price: 105,
    description: "A tree that spans the cosmos",
  },

  // Stones - Based on size and visual complexity
  {
    id: "stone-1",
    name: "Simple Stone",
    image: "/village-items/decor/stones_1.png",
    category: "decor",
    price: 20,
    description: "A basic decorative stone",
  },
  {
    id: "stone-2",
    name: "Mystical Stone",
    image: "/village-items/decor/stones_2.png",
    category: "decor",
    price: 25,
    description: "A stone of mystical power",
  },
  {
    id: "stone-3",
    name: "Ancient Stone",
    image: "/village-items/decor/stones_3.png",
    category: "decor",
    price: 30,
    description: "A stone from ancient times",
  },
  {
    id: "stone-4",
    name: "Magical Stone",
    image: "/village-items/decor/stones_4.png",
    category: "decor",
    price: 35,
    description: "A stone of magical essence",
  },
  {
    id: "stone-5",
    name: "Enchanted Stone",
    image: "/village-items/decor/stones_5.png",
    category: "decor",
    price: 40,
    description: "A stone touched by magic",
  },
  {
    id: "stone-6",
    name: "Legendary Stone",
    image: "/village-items/decor/stones_6.png",
    category: "decor",
    price: 45,
    description: "A stone of legendary power",
  },
  {
    id: "stone-7",
    name: "Divine Stone",
    image: "/village-items/decor/stones_7.png",
    category: "decor",
    price: 50,
    description: "A stone blessed by divinity",
  },

  // Greenery - Based on visual complexity and rarity
  {
    id: "greenery-1",
    name: "Simple Plant",
    image: "/village-items/decor/greenery_1.png",
    category: "decor",
    price: 30,
    description: "A basic decorative plant",
  },
  {
    id: "greenery-2",
    name: "Vibrant Bush",
    image: "/village-items/decor/greenery_2.png",
    category: "decor",
    price: 35,
    description: "A colorful decorative bush",
  },
  {
    id: "greenery-3",
    name: "Exotic Plant",
    image: "/village-items/decor/greenery_3.png",
    category: "decor",
    price: 40,
    description: "An exotic decorative plant",
  },
  {
    id: "greenery-4",
    name: "Mystical Plant",
    image: "/village-items/decor/greenery_4.png",
    category: "decor",
    price: 45,
    description: "A plant of mystical power",
  },
  {
    id: "greenery-5",
    name: "Enchanted Plant",
    image: "/village-items/decor/greenery_5.png",
    category: "decor",
    price: 50,
    description: "A plant touched by magic",
  },
  {
    id: "greenery-6",
    name: "Rare Plant",
    image: "/village-items/decor/greenery_6.png",
    category: "decor",
    price: 55,
    description: "A rare decorative plant",
  },
  {
    id: "greenery-7",
    name: "Exotic Bush",
    image: "/village-items/decor/greenery_7.png",
    category: "decor",
    price: 60,
    description: "An exotic decorative bush",
  },
  {
    id: "greenery-8",
    name: "Magical Shrub",
    image: "/village-items/decor/greenery_8.png",
    category: "decor",
    price: 65,
    description: "A shrub of magical essence",
  },
  {
    id: "greenery-9",
    name: "Enchanted Bush",
    image: "/village-items/decor/greenery_9.png",
    category: "decor",
    price: 70,
    description: "A bush touched by magic",
  },
  {
    id: "greenery-10",
    name: "Mystical Plant",
    image: "/village-items/decor/greenery_10.png",
    category: "decor",
    price: 75,
    description: "A plant of mystical power",
  },
  {
    id: "greenery-11",
    name: "Sacred Bush",
    image: "/village-items/decor/greenery_11.png",
    category: "decor",
    price: 80,
    description: "A bush of sacred power",
  },
  {
    id: "greenery-12",
    name: "Divine Plant",
    image: "/village-items/decor/greenery_12.png",
    category: "decor",
    price: 85,
    description: "A plant blessed by divinity",
  },
  {
    id: "greenery-13",
    name: "Celestial Shrub",
    image: "/village-items/decor/greenery_13.png",
    category: "decor",
    price: 90,
    description: "A shrub from the heavens",
  },
  {
    id: "greenery-14",
    name: "Ethereal Plant",
    image: "/village-items/decor/greenery_14.png",
    category: "decor",
    price: 95,
    description: "A plant of ethereal beauty",
  },

  // Lake - Special feature
  {
    id: "lake-1",
    name: "Serene Lake",
    image: "/village-items/decor/lake.png",
    category: "decor",
    price: 200,
    description: "A peaceful lake for your village",
  },
]; 